<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="Variables & Types" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=Session+2+:+Python+Course" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<div align="center"> 
    <a href="https://cognitiveclass.ai/" >
        <img src="https://devai-organization.github.io/DevAI/assets/robot-efd5afb3.png" width="200" align="center">
    </a>
</div>

**Welcome!**  

This notebook will introduce you to the fundamental **data structures in Python**. Data structures are essential for organizing and managing data efficiently. Python provides several built-in data structures, each suited for different use cases.  

In this notebook, you'll learn about:  

- **Lists** ðŸ“œ â€“ Ordered, mutable collections that allow duplicates.  
- **Tuples** ðŸŽ­ â€“ Ordered, immutable collections for fixed data.  
- **Sets** ðŸ”¥ â€“ Unordered collections of unique elements.  
- **Dictionaries** ðŸ“– â€“ Key-value pairs for fast lookups.  

By the end of this notebook, youâ€™ll understand how to use these data structures effectively and perform operations like adding, removing, and accessing data. Letâ€™s get started! ðŸš€

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="Introduction to Data Structures" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=Introduction+to+Data+Structures" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="List in Python" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=List+In+Python" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<p><strong>Welcome!</strong> This notebook will teach you about the lists in the Python Programming Language. By the end of this lab, you'll know the basics list operations in Python, including indexing, list operations and copy/clone list.</p>

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#dataset">About the Dataset</a>
        </li>
        <li>
            <a href="#list">Lists</a>
            <ul>
                <li><a href="index">Indexing</a></li>
                <li><a href="content">List Content</a></li>
                <li><a href="op">List Operations</a></li>
                <li><a href="co">Copy and Clone List</a></li>
            </ul>
        </li>
        <li>
            <a href="#quiz">Quiz on Lists</a>
        </li>
    </ul>
    <p>
        Estimated time needed: <strong>15 min</strong>
    </p>
</div>

<hr>

<h2 id="#dataset">About the Dataset</h2>

Imagine you received album recommendations from your friends and compiled all of the recommandations into a table, with specific information about each album.

The table has one row for each movie and several columns:

- **artist** - Name of the artist
- **album** - Name of the album
- **released_year** - Year the album was released
- **length_min_sec** - Length of the album (hours,minutes,seconds)
- **genre** - Genre of the album
- **music_recording_sales_millions** - Music recording sales (millions in USD)
- **claimed_sales_millions** - Album's claimed sales (millions in USD)
- **date_released** - Date on which the album was released
- **soundtrack** - Indicates if the album is the movie soundtrack (Y) or (N)
- **rating_of_friends** - Indicates the rating from your friends from 1 to 10
<br>
<br>

The dataset can be seen below:

<font size="1">
<table font-size:xx-small style="width:25%">
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

<h2 id="list">Lists</h2>

<h3 id="index">Indexing</h3>

We are going to take a look at lists in Python. A list is a sequenced collection of different objects such as integers, strings, and other lists as well. The address of each element within a list is called an <b>index</b>. An index is used to access and refer to items within a list.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsIndex.png" width="1000" />

 To create a list, type the list within square brackets <b>[ ]</b>, with your content inside the parenthesis and separated by commas. Letâ€™s try it!

In [106]:
# Create a list

L = ["Michael Jackson", 10.1, 1982]
L

['Michael Jackson', 10.1, 1982]

We can use negative and regular indexing with a list :

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsNeg.png" width="1000" />

In [107]:
# Print the elements on each index

print('the same element using negative and positive indexing:\n Postive:',L[0],
'\n Negative:' , L[-3]  )
print('the same element using negative and positive indexing:\n Postive:',L[1],
'\n Negative:' , L[-2]  )
print('the same element using negative and positive indexing:\n Postive:',L[2],
'\n Negative:' , L[-1]  )

the same element using negative and positive indexing:
 Postive: Michael Jackson
 Negative: Michael Jackson
the same element using negative and positive indexing:
 Postive: 10.1
 Negative: 10.1
the same element using negative and positive indexing:
 Postive: 1982
 Negative: 1982

<h3 id="content">List Content</h3>

Lists can contain strings, floats, and integers. We can nest other lists, and we can also nest tuples and other data structures. The same indexing conventions apply for nesting:

In [108]:
# Sample List

["Michael Jackson", 10.1, 1982, [1, 2], ("A", 1)]

['Michael Jackson', 10.1, 1982, [1, 2], ('A', 1)]

<h3 id="op">List Operations</h3>

 We can also perform slicing in lists. For example, if we want the last two elements, we use the following command:

In [109]:
# Sample List

L = ["Michael Jackson", 10.1,1982,"MJ",1]
L

['Michael Jackson', 10.1, 1982, 'MJ', 1]

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsSlice.png" width="1000">

In [110]:
L = "osama"

L[6:]

''

In [111]:
# List slicing

L[3:5]

'ma'

### `list.append()`

Another similar method is <code>append</code>. If we apply <code>append</code> instead of <code>extend</code>, we add one element to the list:

In [112]:
# Use append to add elements to list

L = [ "Michael Jackson", 10.2]
L.append(['pop', 10])
L

['Michael Jackson', 10.2, ['pop', 10]]

If we append the list  <code>['a','b']</code> we have one new element consisting of a nested list:

In [113]:
# Use append to add elements to list

L.append(['a','b'])
L

['Michael Jackson', 10.2, ['pop', 10], ['a', 'b']]

In [114]:
L = [ "Osama", "Mohamed", "Ahmed", "Sara", "Ali" ]
L.extend("Nora")
L

['Osama', 'Mohamed', 'Ahmed', 'Sara', 'Ali', 'N', 'o', 'r', 'a']

### `list.extend()`

We can use the method <code>extend</code> to add new elements to the list:

In [115]:
# Use extend to add elements to list

L = [ "Michael Jackson", 10.2]
L.extend(['pop', 10])
L

['Michael Jackson', 10.2, 'pop', 10]

 Each time we apply a method, the list changes. If we apply <code>extend</code> we add two new elements to the list. The list <code>L</code> is then modified by adding two new elements:

In [116]:
# Use extend to add elements to list

L = [ "Michael Jackson", 10.2]
L.extend(['pop', 10])
L

['Michael Jackson', 10.2, 'pop', 10]

### List are mutable

As lists are mutable, we can change them. For example, we can change the first element as follows:

In [117]:
# Change the element based on the index

A = ["disco", 10, 1.2]
print('Before change:', A)
A[0] = 'hard rock'
print('After change:', A)

Before change: ['disco', 10, 1.2]
After change: ['hard rock', 10, 1.2]

### `del`

 We can also delete an element of a list using the <code>del</code> command:

In [118]:
# Delete the element based on the index

print('Before change:', A)
del(A[0])
print('After change:', A)

Before change: ['hard rock', 10, 1.2]
After change: [10, 1.2]

### `list.remove()`

In [119]:
my_list = ["Python", "is", "sometimes", "fun"]
my_list.remove("sometimes")
print(my_list)

# If you are not sure that the value is in list, better to check first:
if "Java" in my_list:
    my_list.remove("Java")
else:
    print("Java is not part of this story.")

['Python', 'is', 'fun']
Java is not part of this story.

### `sorted`

`sorted(list)` returns a new sorted list and leaves the original untouched

In [120]:
numbers = [8, 1, 6, 5, 10]
sorted_numbers = sorted(numbers)
print(f"{numbers=}, {sorted_numbers=}")

numbers=[8, 1, 6, 5, 10], sorted_numbers=[1, 5, 6, 8, 10]

### `list.sort()`

`list.sort()` sorts the list in-place modify the original list

In [121]:
numbers = [8, 1, 6, 5, 10]
numbers.sort()
print(f"numbers: {numbers}")

numbers.sort(reverse=True)
print(f"numbers reversed: {numbers}")

words = ["this", "is", "a", "list", "of", "words"]
words.sort()
print(f"words: {words}")

numbers: [1, 5, 6, 8, 10]
numbers reversed: [10, 8, 6, 5, 1]
words: ['a', 'is', 'list', 'of', 'this', 'words']

### `list.reverse()`

In [122]:
my_list = ["a", "b", "ham"]
my_list.reverse()
print(my_list)

['ham', 'b', 'a']

<h3 id="co">Copy and Clone List</h3>

When we set one variable <b>B</b> equal to <b>A</b>; both <b>A</b> and <b>B</b> are referencing the same list in memory:

In [123]:
# Copy (copy by reference) the list A

A = ["hard rock", 10, 1.2]
B = A
print('A:', A)
print('B:', B)

A: ['hard rock', 10, 1.2]
B: ['hard rock', 10, 1.2]

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsRef.png" width="1000" align="center">

Initially, the value of the first element in <b>B</b> is set as hard rock. If we change the first element in <b>A</b> to <b>banana</b>, we get an unexpected side effect.  As <b>A</b> and <b>B</b> are referencing the same list, if we change list <b>A</b>, then list <b>B</b> also changes. If we check the first element of <b>B</b> we get banana instead of hard rock:

In [124]:
print(id(A[0]))
print(id(A[1]))
print(id(A[2]))

1599013566512
1598923014672
1599017536304

In [125]:
print(id(B[0]))
print(id(B[1]))
print(id(B[2]))

1599013566512
1598923014672
1599017536304

In [126]:
print(id(B))
print(id(A))

1599012779776
1599012779776

In [127]:
A is B

True

In [128]:
A == B

True

In [129]:
# Examine the copy by reference

print('B[0]:', B[0])
A[0] = "banana"
print('B[0]:', B[0])

B[0]: hard rock
B[0]: banana

This is demonstrated in the following figure:

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsRefGif.gif" width="1000" />

You can clone list  **A** by using  the following syntax:

In [130]:
# Clone (clone by value) the list A

B = A[:]
B

['banana', 10, 1.2]

 Variable **B** references a new copy or clone of the original list; this is demonstrated in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsVal.gif" width="1000" />

Now if you change <b>A</b>, <b>B</b> will not change:

In [131]:
print(id(A[0]))
print(id(A[1]))
print(id(A[2]))

1599005941040
1598923014672
1599017536304

In [132]:
print(id(B[0]))
print(id(B[1]))
print(id(B[2]))

1599005941040
1598923014672
1599017536304

In [133]:
print(id(B))
print(id(A))

1599013656960
1599012779776

In [134]:
A is B

False

In [135]:
A == B

True

In [136]:
print('B[0]:', B[0])
A[0] = "hard rock"
print('B[0]:', B[0])

B[0]: banana
B[0]: banana

In [160]:
print(id(A[0]))
print(id(B[0]))

1599013474736
1599005941040

In [161]:
print(id(B[0]))
print(id(B[1]))
print(id(B[2]))

1599005941040
1598923014672
1599017536304

In [162]:
print(id(A[0]))
print(id(A[1]))
print(id(A[2]))

1599013474736
1598923014672
1599017536304

<h2 id="quiz">Quiz on List</h2>

Create a list <code>a_list</code>, with the following elements <code>1</code>, <code>hello</code>, <code>[1,2,3]</code> and <code>True</code>.

In [137]:
# Write your code below and press Shift+Enter to execute

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
a_list = [1, 'hello', [1, 2, 3] , True]
a_list
-->

Find the value stored at index 1 of <code>a_list</code>.

In [138]:
# Write your code below and press Shift+Enter to execute

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
a_list[1]
-->

Retrieve the elements stored at index 1, 2 and 3 of <code>a_list</code>.

In [139]:
# Write your code below and press Shift+Enter to execute

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
a_list[1:4]
-->

Concatenate the following lists <code>A = [1, 'a']</code> and <code>B = [2, 1, 'd']</code>:

In [140]:
# Write your code below and press Shift+Enter to execute

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
A = [1, 'a'] 
B = [2, 1, 'd']
A + B
-->

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="Tuple in Python" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=Tuple+In+Python" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<p><strong>Welcome!</strong> This notebook will teach you about the tuples in the Python Programming Language. By the end of this lab, you'll know the basics tuple operations in Python, including indexing, slicing and sorting.</p>

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#dataset">About the Dataset</a>
        </li>
        <li>
            <a href="#tuple">Tuples</a>
            <ul>
                <li><a href="index">Indexing</a></li>
                <li><a href="slice">Slicing</a></li>
                <li><a href="sort">Sorting</a></li>
                <li><a href="Modification">Modification</a></i>
            </ul>
        </li>
        <li>
            <a href="#escape">Quiz on Tuples</a>
        </li>
    </ul>
    <p>
        Estimated time needed: <strong>15 min</strong>
    </p>
</div>

<hr>

<h2 id="dataset">About the Dataset</h2>

Imagine you received album recommendations from your friends and compiled all of the recommandations into a table, with specific information about each album.

The table has one row for each movie and several columns:

- **artist** - Name of the artist
- **album** - Name of the album
- **released_year** - Year the album was released
- **length_min_sec** - Length of the album (hours,minutes,seconds)
- **genre** - Genre of the album
- **music_recording_sales_millions** - Music recording sales (millions in USD)
- **claimed_sales_millions** - Album's claimed sales (millions in USD)
- **date_released** - Date on which the album was released
- **soundtrack** - Indicates if the album is the movie soundtrack (Y) or (N)
- **rating_of_friends** - Indicates the rating from your friends from 1 to 10
<br>
<br>

The dataset can be seen below:

<font size="1">
<table font-size:xx-small style="width:25%">
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

<h2 id="tuple">Tuples</h2>

In Python, there are different data types: string, integer and float. These data types can all be contained in a tuple as follows:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesType.png" width="750" align="center" />

Now, let us create your first tuple with string, integer and float.

In [141]:
# Create your first tuple

tuple1 = ("disco",10,1.2 )
tuple1

('disco', 10, 1.2)

The type of variable is a **tuple**.

In [142]:
# Print the type of the tuple you created

type(tuple1)

tuple

<h3 id="index">Indexing</h3>

 Each element of a tuple can be accessed via an index. The following table represents the relationship between the index and the items in the tuple. Each element can be obtained by the name of the tuple followed by a square bracket with the index number:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesIndex.gif" width="750" align="center">

We can print out each value in the tuple:

In [143]:
# Print the variable on each index

print(tuple1[0])
print(tuple1[1])
print(tuple1[2])

disco
10
1.2

We can print out the **type** of each value in the tuple:

In [144]:
# Print the type of value on each index

print(type(tuple1[0]))
print(type(tuple1[1]))
print(type(tuple1[2]))

<class 'str'>
<class 'int'>
<class 'float'>

We can also use negative indexing. We use the same table above with corresponding negative values:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNeg.png" width="750" align="center">

We can obtain the last element as follows (this time we will not use the print statement to display the values):

In [145]:
# Use negative index to get the value of the last element

tuple1[-1]

1.2

We can display the next two elements as follows:

In [146]:
# Use negative index to get the value of the second last element

tuple1[-2]

10

In [147]:
# Use negative index to get the value of the third last element

tuple1[-3]

'disco'

<h3 id="concate">Concatenate Tuples</h3>

We can concatenate or combine tuples by using the **+** sign:

In [148]:
# Concatenate two tuples

tuple2 = tuple1 + ("hard rock", 10)
tuple2

('disco', 10, 1.2, 'hard rock', 10)

We can slice tuples obtaining multiple values as demonstrated by the figure below:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesSlice.gif" width="750" align="center">

<h3 id="slice">Slicing</h3>

We can slice tuples, obtaining new tuples with the corresponding elements:

In [149]:
# Slice from index 0 to index 2

tuple2[0:3]

('disco', 10, 1.2)

We can obtain the last two elements of the tuple:

In [150]:
# Slice from index 3 to index 4

tuple2[3:5]

('hard rock', 10)

We can obtain the length of a tuple using the length command:

In [151]:
# Get the length of tuple

len(tuple2)

5

This figure shows the number of elements:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesElement.png" width="750" align="center">

<h3 id="sort">Sorting</h3>

 Consider the following tuple:

In [152]:
# A sample tuple

Ratings = (0, 9, 6, 5, 10, 8, 9, 6, 2)

We can sort the values in a tuple and save it to a new tuple:

In [153]:
# Sort the tuple

RatingsSorted = sorted(Ratings)
RatingsSorted

[0, 2, 5, 6, 6, 8, 9, 9, 10]

<h3 id="nest">Nested Tuple</h3>

A tuple can contain another tuple as well as other more complex data types. This process is called 'nesting'. Consider the following tuple with several elements:

In [154]:
# Create a nest tuple

NestedT =(1, 2, ("pop", "rock") ,(3,4),("disco",(1,2)))

Each element in the tuple including other tuples can be obtained via an index as shown in the figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestOne.png" width="750" align="center">

In [155]:
# Print element on each index

print("Element 0 of Tuple: ", NestedT[0])
print("Element 1 of Tuple: ", NestedT[1])
print("Element 2 of Tuple: ", NestedT[2])
print("Element 3 of Tuple: ", NestedT[3])
print("Element 4 of Tuple: ", NestedT[4])

Element 0 of Tuple:  1
Element 1 of Tuple:  2
Element 2 of Tuple:  ('pop', 'rock')
Element 3 of Tuple:  (3, 4)
Element 4 of Tuple:  ('disco', (1, 2))

We can use the second index to access other tuples as demonstrated in the figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestTwo.png" width="750" align="center">

 We can access the nested tuples :

In [156]:
# Print element on each index, including nest indexes

print("Element 2, 0 of Tuple: ",   NestedT[2][0])
print("Element 2, 1 of Tuple: ",   NestedT[2][1])
print("Element 3, 0 of Tuple: ",   NestedT[3][0])
print("Element 3, 1 of Tuple: ",   NestedT[3][1])
print("Element 4, 0 of Tuple: ",   NestedT[4][0])
print("Element 4, 1 of Tuple: ",   NestedT[4][1])

Element 2, 0 of Tuple:  pop
Element 2, 1 of Tuple:  rock
Element 3, 0 of Tuple:  3
Element 3, 1 of Tuple:  4
Element 4, 0 of Tuple:  disco
Element 4, 1 of Tuple:  (1, 2)

We can access strings in the second nested tuples using a third index:

In [157]:
# Print the first element in the second nested tuples

NestedT[2][1][0]

'r'

In [158]:
# Print the second element in the second nested tuples

NestedT[2][1][1]

'o'

In [159]:
S = "School"
S[0] = "O"
print(S)

TypeError: 'str' object does not support item assignment

 We can use a tree to visualise the process. Each new index corresponds to a deeper level in the tree:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestThree.gif" width="750" align="center">

Similarly, we can access elements nested deeper in the tree with a fourth index:

In [ ]:
# Print the first element in the second nested tuples

NestedT[4][1][0]

1

In [ ]:
# Print the second element in the second nested tuples

NestedT[4][1][1]

2

The following figure shows the relationship of the tree and the element <code>NestedT[4][1][1]</code>:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesNestFour.gif" width="750" align="center">

### Tuple Modification

In [ ]:
# You can't change the elements in a tuple, but you can replace one tuple with another
# Convert the table headers to a tuple
table_headers = ("Artist", "Album", "Released", "Length", "Genre", 
                 "Music recording sales (millions)", "Claimed sales (millions)", 
                 "Released", "Soundtrack", "Rating (friends)")
# Replace the element on index 2

table_headers[0] = "Singer"
print(table_headers)

TypeError: 'tuple' object does not support item assignment

<h2 id="quiz">Quiz on Tuples</h2>

Consider the following tuple:

In [ ]:
# sample tuple

genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", \
                "R&B", "progressive rock", "disco") 
genres_tuple

('pop',
 'rock',
 'soul',
 'hard rock',
 'soft rock',
 'R&B',
 'progressive rock',
 'disco')

Find the length of the tuple, <code>genres_tuple</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/TuplesQuiz.png" width="1100" align="center">

Double-click __here__ for the solution.

<!-- Your answer is below:
len(genres_tuple)
-->

Access the element, with respect to index 3:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
genres_tuple[3]
-->

Use slicing to obtain indexes 3, 4 and 5:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
genres_tuple[3:6]
-->

Find the first two elements of the tuple <code>genres_tuple</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
genres_tuple[0:2]
-->

Find the first index of <code>"disco"</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
genres_tuple.index("disco")
-->

Generate a sorted List from the Tuple <code>C_tuple=(-5, 1, -3)</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
C_tuple = (-5, 1, -3)
C_list = sorted(C_tuple)
C_list
-->

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="Dict in Python" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=Dict+In+Python" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<p><strong>Welcome!</strong> This notebook will teach you about the dictionaries in the Python Programming Language. By the end of this lab, you'll know the basics dictionary operations in Python, including what it is, and the operations on it.</p>

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#dic">Dictionaries</a>
            <ul>
                <li><a href="content">What are Dictionaries?</a></li>
                <li><a href="key">Keys</a></li>
            </ul>
        </li>
        <li>
            <a href="#quiz">Quiz on Dictionaries</a>
        </li>
    </ul>
    <p>
        Estimated time needed: <strong>20 min</strong>
    </p>
</div>

<hr>

<h2 id="Dic">Dictionaries</h2>

<h3 id="content">What are Dictionaries?</h3>

A dictionary consists of keys and values. It is helpful to compare a dictionary to a list. Instead of the numerical indexes such as a list, dictionaries have keys. These keys are the keys that are used to access values within a dictionary.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsList.png" width="650" />

An example of a Dictionary <code>Dict</code>:

In [163]:
# Create the dictionary

Dict = {"key1": 1, "key2": "2", "key3": [3, 3, 3], "key4": (4, 4, 4), ('key5'): 5, (0, 1): 6}
Dict

{'key1': 1,
 'key2': '2',
 'key3': [3, 3, 3],
 'key4': (4, 4, 4),
 'key5': 5,
 (0, 1): 6}

The keys can be strings:

In [164]:
# Access to the value by the key

Dict["key1"]

1

Keys can also be any immutable object such as a tuple:

In [165]:
# Access to the value by the key

Dict[(0, 1)]

6

In [166]:
Dict = {{1,0}:4}
Dict[{1,0}]

TypeError: unhashable type: 'set'

 Each key is separated from its value by a colon "<code>:</code>".  Commas separate the items, and the whole dictionary is enclosed in curly braces. An empty dictionary without any items is written with just two curly braces, like this  "<code>{}</code>".

In [167]:
# Create a sample dictionary

release_year_dict = {"Thriller": "1982", "Back in Black": "1980", \
                    "The Dark Side of the Moon": "1973", "The Bodyguard": "1992", \
                    "Bat Out of Hell": "1977", "Their Greatest Hits (1971-1975)": "1976", \
                    "Saturday Night Fever": "1977", "Rumours": "1977"}
release_year_dict

{'Thriller': '1982',
 'Back in Black': '1980',
 'The Dark Side of the Moon': '1973',
 'The Bodyguard': '1992',
 'Bat Out of Hell': '1977',
 'Their Greatest Hits (1971-1975)': '1976',
 'Saturday Night Fever': '1977',
 'Rumours': '1977'}

In summary, like a list, a dictionary holds a sequence of elements. Each element is represented by a key and its corresponding value. Dictionaries are created with two curly braces containing keys and values separated by a colon. For every key, there can only be one single value, however,  multiple keys can hold the same value. Keys can only be strings, numbers, or tuples, but values can be any data type.

It is helpful to visualize the dictionary as a table, as in the following image. The first column represents the keys, the second column represents the values.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsStructure.png" width="650" />

<h3 id="key">Keys</h3>

You can retrieve the values based on the names:

In [168]:
# Get value by keys

release_year_dict['Thriller']

'1982'

This corresponds to:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsKeyOne.png" width="500" />

Similarly for <b>The Bodyguard</b>

In [169]:
# Get value by key

release_year_dict['The Bodyguard']

'1992'

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsKeyTwo.png" width="500" />

### `dict.keys(), dict.values(), dict.items()`

Now let you retrieve the keys of the dictionary using the method <code>release_year_dict()</code>:

In [170]:
# Get all the keys in dictionary

release_year_dict.keys()

dict_keys(['Thriller', 'Back in Black', 'The Dark Side of the Moon', 'The Bodyguard', 'Bat Out of Hell', 'Their Greatest Hits (1971-1975)', 'Saturday Night Fever', 'Rumours'])

You can retrieve the values using the method  <code>values()</code>:

In [171]:
# Get all the values in dictionary

release_year_dict.values()

dict_values(['1982', '1980', '1973', '1992', '1977', '1976', '1977', '1977'])

### Accessing and setting values

### `dict.update()`
Merge two `dict`s

In [172]:
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3}
dict1.update(dict2)
print(dict1)

# If they have same keys:
dict1.update({"c": 4})
print(dict1)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 4}

We can add an entry:

In [173]:
# Append value with key into dictionary

release_year_dict['Graduation'] = '2007'
release_year_dict

{'Thriller': '1982',
 'Back in Black': '1980',
 'The Dark Side of the Moon': '1973',
 'The Bodyguard': '1992',
 'Bat Out of Hell': '1977',
 'Their Greatest Hits (1971-1975)': '1976',
 'Saturday Night Fever': '1977',
 'Rumours': '1977',
 'Graduation': '2007'}

<a id='dict_get'></a>
### `dict.get()`
Returns `None` if `key` is not in `dict`. However, you can also specify `default` return value which will be returned if `key` is not present in the `dict`.

In [174]:
my_dict = {"a": 1, "b": 2, "c": 3}
value_of_d = my_dict.get("d")
print(f"d: {value_of_d}")

value_of_d = my_dict.get("d", "my default value")
print(f"d: {value_of_d}")

d: None
d: my default value

### `dict.pop()`

In [175]:
my_dict = dict(food="ham", drink="beer", sport="football")
print(f"dict before pops: {my_dict}")

food = my_dict.pop("food")
print(f"food: {food}")
print(f"dict after popping food: {my_dict}")

food_again = my_dict.pop("food", "default value for food")
print(f"food again: {food_again}")
print(f"dict after popping food again: {my_dict}")

dict before pops: {'food': 'ham', 'drink': 'beer', 'sport': 'football'}
food: ham
dict after popping food: {'drink': 'beer', 'sport': 'football'}
food again: default value for food
dict after popping food again: {'drink': 'beer', 'sport': 'football'}

We can delete an entry:

In [176]:
# Delete entries by key

del(release_year_dict['Thriller'])
del(release_year_dict['Graduation'])
release_year_dict

{'Back in Black': '1980',
 'The Dark Side of the Moon': '1973',
 'The Bodyguard': '1992',
 'Bat Out of Hell': '1977',
 'Their Greatest Hits (1971-1975)': '1976',
 'Saturday Night Fever': '1977',
 'Rumours': '1977'}

 We can verify if an element is in the dictionary:

In [177]:
# Verify the key is in the dictionary

'The Bodyguard' in release_year_dict

True

### The keys of a `dict` have to be immutable

Thus you can not use e.g. a `list` or a `dict` as key because they are mutable types
:

In [178]:
# bad_dict = {['my_list'], 'value'}  # Raises TypeError

Values can be mutable

In [179]:
good_dict = {"my key": ["Python", "is", "still", "cool"]}
print(good_dict)

{'my key': ['Python', 'is', 'still', 'cool']}

<h2 id="quiz">Quiz on Dictionaries</h2>

<b>You will need this dictionary for the next two questions:</b>

In [180]:
# Question sample dictionary

soundtrack_dic = {"The Bodyguard":"1992", "Saturday Night Fever":"1977"}
soundtrack_dic

{'The Bodyguard': '1992', 'Saturday Night Fever': '1977'}

a) In the dictionary <code>soundtrack_dict</code> what are the keys ?

In [181]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
soundtrack_dic.keys() # The Keys "The Bodyguard" and "Saturday Night Fever" 
-->

b) In the dictionary <code>soundtrack_dict</code> what are the values ?

In [182]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
soundtrack_dic.values() # The values are "1992" and "1977"
-->

<hr>

The Albums <b>Back in Black</b>, <b>The Bodyguard</b> and <b>Thriller</b> have the following music recording sales in millions 50, 50 and 65 respectively:

a) Create a dictionary <code>album_sales_dict</code> where the keys are the album name and the sales in millions are the values.

In [183]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict = {"The Bodyguard":50, "Back in Black":50, "Thriller":65}
-->

b) Use the dictionary to find the total sales of <b>Thriller</b>:

In [184]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict["Thriller"]
-->

c) Find the names of the albums from the dictionary using the method <code>keys</code>:

In [185]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict.keys()
-->

d) Find the names of the recording sales from the dictionary using the method <code>values</code>:

In [186]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict.values()
-->

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="List in Python" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=Set+In+Python" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<p><strong>Welcome!</strong> This notebook will teach you about the sets in the Python Programming Language. By the end of this lab, you'll know the basics set operations in Python, including what it is, operations and logic operations.</p>

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#set">Sets</a>
            <ul>
                <li><a href="content">Set Content</a></li>
                <li><a href="op">Set Operations</a></li>
                <li><a href="logic">Sets Logic Operations</a></li>
            </ul>
        </li>
        <li>
            <a href="#quiz">Quiz on Sets</a>
        </li>
    </ul>
    <p>
        Estimated time needed: <strong>20 min</strong>
    </p>
</div>

<hr>

<h2 id="set">Sets</h2>

<h3 id="content">Set Content</h3>

A set is a unique collection of objects in Python. You can denote a set with a curly bracket <b>{}</b>. Python will automatically remove duplicate items:

In [187]:
# Create a set

set1 = {"pop", "rock", "soul", "hard rock", "rock", "R&B", "rock", "disco"}
set1

{'R&B', 'disco', 'hard rock', 'pop', 'rock', 'soul'}

The process of mapping is illustrated in the figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsUnique.png" width="1100" />

 You can also  create a set from a list as follows:

In [188]:
# Convert list to set

album_list = [ "Michael Jackson", "Thriller", 1982, "00:42:19", \
              "Pop, Rock, R&B", 46.0, 65, "30-Nov-82", None, 10.0]
album_set = set(album_list)             
album_set

{'00:42:19',
 10.0,
 1982,
 '30-Nov-82',
 46.0,
 65,
 'Michael Jackson',
 None,
 'Pop, Rock, R&B',
 'Thriller'}

Now let us create a set of  genres:

In [189]:
# Convert list to set

music_genres = set(["pop", "pop", "rock", "folk rock", "hard rock", "soul", \
                    "progressive rock", "soft rock", "R&B", "disco"])
music_genres

{'R&B',
 'disco',
 'folk rock',
 'hard rock',
 'pop',
 'progressive rock',
 'rock',
 'soft rock',
 'soul'}

<h3 id="op">Set Operations</h3>

Let us go over set operations, as these can be used to change the set. Consider the set <b>A</b>:

In [190]:
# Sample set

A = set(["Thriller", "Back in Black", "AC/DC"])
A

{'AC/DC', 'Back in Black', 'Thriller'}

 We can add an element to a set using the <code>add()</code> method:

In [191]:
# Add element to set

A.add("NSYNC")
A

{'AC/DC', 'Back in Black', 'NSYNC', 'Thriller'}

 If we add the same element twice, nothing will happen as there can be no duplicates in a set:

In [192]:
# Try to add duplicate element to the set

A.add("NSYNC")
A

{'AC/DC', 'Back in Black', 'NSYNC', 'Thriller'}

 We can remove an item from a set using the <code>remove</code> method:

In [193]:
# Remove the element from set

A.remove("NSYNC")
A

{'AC/DC', 'Back in Black', 'Thriller'}

 We can verify if an element is in the set using the <code>in</code> command:

In [194]:
# Verify if the element is in the set

"AC/DC" in A

True

<h3 id="logic">Sets Logic Operations</h3>

Remember that with sets you can check the difference between sets, as well as the symmetric difference, intersection, and union:

 Consider the following two sets:

In [195]:
# Sample Sets

album_set1 = set(["Thriller", 'AC/DC', 'Back in Black'])
album_set2 = set([ "AC/DC", "Back in Black", "The Dark Side of the Moon"])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsSamples.png" width="650" />

In [196]:
# Print two sets

album_set1, album_set2

({'AC/DC', 'Back in Black', 'Thriller'},
 {'AC/DC', 'Back in Black', 'The Dark Side of the Moon'})

As both sets contain <b>AC/DC</b> and <b>Back in Black</b> we represent these common elements with the intersection of two circles.

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsLogic.png" width = "650" />

You can find the Union of two sets as follow using <code>&</code>:

In [197]:
# Find the Union

Union = album_set1.union(album_set2)
Union

{'AC/DC', 'Back in Black', 'The Dark Side of the Moon', 'Thriller'}

In [198]:
# Find the Union

album_set1 | album_set2

{'AC/DC', 'Back in Black', 'The Dark Side of the Moon', 'Thriller'}

You can find all the elements that are only contained in <code>album_set1</code> using the <code>difference</code> method:

In [199]:
# Find the difference in set1 but not set2

album_set1.difference(album_set2)

{'Thriller'}

In [200]:
album_set1 - album_set2

{'Thriller'}

You only need to consider elements in <code>album_set1</code>; all the elements in <code>album_set2</code>, including the intersection, are not included.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsLeft.png" width="650" />

The elements in <code>album_set2</code> but not in <code>album_set1</code> is given by:

In [201]:
album_set2.difference(album_set1)

{'The Dark Side of the Moon'}

In [202]:
album_set2 - album_set1

{'The Dark Side of the Moon'}

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsRight.png" width="650" />

You can also find the intersection of <code>album_list1</code> and <code>album_list2</code>, using the <code>intersection</code> method:

In [203]:
# Use intersection method to find the intersection of album_list1 and album_list2

album_set1.intersection(album_set2)

{'AC/DC', 'Back in Black'}

 This corresponds to the intersection of the two circles:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsIntersect.png" width="650" />

In [204]:
album_set1.symmetric_difference(album_set2)

{'The Dark Side of the Moon', 'Thriller'}

In [205]:
album_set1 ^ album_set2

{'The Dark Side of the Moon', 'Thriller'}

The union corresponds to all the elements in both sets, which is represented by coloring both circles:

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/SetsUnion.png" width="650" />

 The union is given by:

In [206]:
# Find the union of two sets

album_set1.union(album_set2)

{'AC/DC', 'Back in Black', 'The Dark Side of the Moon', 'Thriller'}

In [207]:
album_set1 & album_set2

{'AC/DC', 'Back in Black'}

And you can check if a set is a superset or subset of another set, respectively, like this:

In [208]:
# Check if superset

set(album_set1).issuperset(album_set2)

False

In [209]:
album_set1 <= album_set2

False

In [210]:
# Check if subset

set(album_set2).issubset(album_set1)

False

In [211]:
album_set1 >= album_set2

False

Here is an example where <code>issubset()</code> and <code>issuperset()</code> return true:

In [212]:
# Check if subset

set({"Back in Black", "AC/DC"}).issubset(album_set1)

True

In [213]:
# Check if superset

album_set1.issuperset({"Back in Black", "AC/DC"})

True

<hr>

<h2 id="quiz">Quiz on Sets</h2>

Convert the list <code>['rap','house','electronic music', 'rap']</code> to a set:

In [214]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.
<!-- Your answer is below:
set(['rap','house','electronic music','rap'])
-->

<hr>

Consider the list <code>A = [1, 2, 2, 1]</code> and set <code>B = set([1, 2, 2, 1])</code>, does <code>sum(A) = sum(B)</code>

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
A = [1, 2, 2, 1]  
B = set([1, 2, 2, 1])
print("the sum of A is:", sum(A))
print("the sum of B is:", sum(B))
-->

<hr>

Create a new set <code>album_set3</code> that is the union of <code>album_set1</code> and <code>album_set2</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

album_set1 = set(["Thriller", 'AC/DC', 'Back in Black'])
album_set2 = set([ "AC/DC", "Back in Black", "The Dark Side of the Moon"])

Double-click __here__ for the solution.

<!-- Your answer is below:
album_set3 = album_set1.union(album_set2)
album_set3
-->

<hr>

Find out if <code>album_set1</code> is a subset of <code>album_set3</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.

<!-- Your answer is below:
album_set1.issubset(album_set3)
-->

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif"> 
<div align="center">
    <a href="https://git.io/typing-svg">
        <img alt="End of the notebook" src="https://readme-typing-svg.demolab.com?font=Roboto+Slab&size=24&pause=1000&color=7E3ACECE&center=true&vCenter=true&width=435&lines=End of This Notebook" >
    </a>
</div>
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first Session In my AI and Data Science Course hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub and Kaggle. By sharing your notebook on GitHub and Kaggle you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits.

<h3>About the Author:</h3>  
<p><a href="https://www.linkedin.com/in/OsamaM0/" target="_blank">Osama Mohamed</a> is a Data Scientist at Margins Developments with a B.Sc. in Computer Science. He has extensive experience in Machine Learning, Deep Learning, Natural Language Processing (NLP), Large Language Models (LLMs), and Computer Vision. Osama specializes in developing and deploying AI-driven solutions across diverse industries, including real estate, education, healthcare, and fitness. With a strong ability to execute AI projects end-to-end, he excels in data preprocessing, model development, deployment, and ongoing monitoring, ensuring scalable and impactful AI solutions.</p>